// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsSFGbqxe4c2F-xLPb5L7x2P9rfGrnMxM',
    appId: '1:790857841475:web:90f9e1d54054ea35be8df6',
    messagingSenderId: '790857841475',
    projectId: 'flutter2-78281',
    authDomain: 'flutter2-78281.firebaseapp.com',
    storageBucket: 'flutter2-78281.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4pvbNwkF9ZDWKJKz6qHkEE5lHGq5xHnE',
    appId: '1:790857841475:android:92b5429043bba8f0be8df6',
    messagingSenderId: '790857841475',
    projectId: 'flutter2-78281',
    storageBucket: 'flutter2-78281.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhz3t-2u_QDuxhRkgeAAIIeKl553fQdXs',
    appId: '1:790857841475:ios:98e3b62a6e8a7c80be8df6',
    messagingSenderId: '790857841475',
    projectId: 'flutter2-78281',
    storageBucket: 'flutter2-78281.firebasestorage.app',
    iosBundleId: 'com.example.flutterProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhz3t-2u_QDuxhRkgeAAIIeKl553fQdXs',
    appId: '1:790857841475:ios:98e3b62a6e8a7c80be8df6',
    messagingSenderId: '790857841475',
    projectId: 'flutter2-78281',
    storageBucket: 'flutter2-78281.firebasestorage.app',
    iosBundleId: 'com.example.flutterProj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsSFGbqxe4c2F-xLPb5L7x2P9rfGrnMxM',
    appId: '1:790857841475:web:085489c9be0009efbe8df6',
    messagingSenderId: '790857841475',
    projectId: 'flutter2-78281',
    authDomain: 'flutter2-78281.firebaseapp.com',
    storageBucket: 'flutter2-78281.firebasestorage.app',
  );
}
